version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unicorn-commander-web
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-7878}:80"  # Use WEB_PORT env var, default to 7878
    networks:
      - unicorn-network
    environment:
      - NODE_ENV=production

networks:
  unicorn-network:
    driver: bridge
