version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magic-unicorn-web
    restart: unless-stopped
    ports:
      - "7878:80"  # This makes it accessible on all networks at port 7878
    networks:
      - magic-network

networks:
  magic-network:
    driver: bridge
